### ISSUE TITLE
need toggle_labels() function

### ISSUE THREAD

**Issue by gukz** [NStefan002/wormhole.nvim#2]
### Problem

Hi I see this plugin has `create_labels()` and `remove_labels()`, can you also add an `toggle_labels()` implement? so I can use one key binding for this plugin, thx

### Expected behavior

can use `toggle_labels()` to toggle the window label's display.

**Comment by NStefan002** [comment]
That makes sense, thanks for the suggestion! I just added this feature. Do you mind testing it?
