### ISSUE TITLE
I don't see any labels :thinking: 

### ISSUE THREAD

**Issue by NullVoxPopuli** [NStefan002/wormhole.nvim#4]
### Problem

When I run
```vim
:lua require('wormhole.labels').toggle_labels()
```
I don't see any labels.

Are there column requirements? 

I tried changing my signcolumn to `yes:1`, but nothing displays even still.

### Neovim version (`nvim -v`)

nightly (2024-11-14)

**Comment by NStefan002** [comment]
Oops, thank you so much for reporting this!

**Comment by NullVoxPopuli** [comment]
perfection! thank you!
